### PR TITLE
Allow url to be an array

### PR DESCRIPTION
**Pull request by zhangtemplar**
In certain library, it may contain multiple files, e.g., [https://unpkg.com/rc-drawer-menu@0.5.7/dist/](https://unpkg.com/rc-drawer-menu@0.5.7/dist/), one for source code, the other for style file or locale file.

### CODE REVIEW

**Comment by aulisius** [comment]
Hi @zhangtemplar , thanks for the PR! All looks good. Can you also add some tests to test against this usecase?

Thanks,
Faizaan.

**Comment by zhangtemplar** [comment]
@aulisius sure, give me some time. I found some problem when running the new test.

**Comment by mastilver** [comment]
Hi @zhangtemplar , thank you for the PR. But I don't think it will work

Please tell me if I'm wrong but with your example `rc-drawer-menu` and without the this webpack plugin, you will need to import each of them one by one; this plugin doesn't change anything and is not suppose to change previous behaviours: if it was working before, it should still work

What we need to do is work on #12 and for module-to-cdn to handle multiple types of assets (css, js, ...)

**Comment by zhangtemplar** [comment]
Got you!

**Comment by mastilver** [comment]
closing that, based on above conversation

**Pull request closed without merging**
